# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Eph < Formula
  desc "Minimal, terminal-native git hosting"
  homepage "https://ephemeral.so"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bantamhq/ephemeral/releases/download/v0.0.1/eph_darwin_amd64.tar.gz"
      sha256 "7f5fb1386847d9be6301e415a28aaa10195de0bef38f3411264f51f1976fcac0"

      def install
        bin.install "eph"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bantamhq/ephemeral/releases/download/v0.0.1/eph_darwin_arm64.tar.gz"
      sha256 "fab1beb7f991deb6b99f2ee364fe28c2b9b8e4dd319d736d3ef13066f0c7763f"

      def install
        bin.install "eph"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bantamhq/ephemeral/releases/download/v0.0.1/eph_linux_amd64.tar.gz"
      sha256 "f5940737531c94458d49057a6f6c2389e8816f21545e1ec907586910b804a56c"
      def install
        bin.install "eph"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bantamhq/ephemeral/releases/download/v0.0.1/eph_linux_arm64.tar.gz"
      sha256 "7786a26754d2d2d90e75498472aa15cfd03e4fa9d9e61804f09cccfdfb796a4f"
      def install
        bin.install "eph"
      end
    end
  end

  test do
    system "#{bin}/eph", "--version"
  end
end
