# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Eph < Formula
  desc "Minimal, terminal-native git hosting"
  homepage "https://ephemeral.so"
  version "0.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bantamhq/ephemeral/releases/download/v0.0.5/eph_darwin_amd64.tar.gz"
      sha256 "b626b5767bbcc1f39c4f94abfb8990efd8277a0403038b095eaaad8445cc71a8"

      def install
        bin.install "eph"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bantamhq/ephemeral/releases/download/v0.0.5/eph_darwin_arm64.tar.gz"
      sha256 "49ca787b4dfbab97be256f191e494a736e5ed464515222207ffd0de789e7e933"

      def install
        bin.install "eph"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bantamhq/ephemeral/releases/download/v0.0.5/eph_linux_amd64.tar.gz"
      sha256 "c58a2021c11d14abf281aa809b0b459eb677e09117c095b6e1c6dd24b65b28e8"
      def install
        bin.install "eph"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bantamhq/ephemeral/releases/download/v0.0.5/eph_linux_arm64.tar.gz"
      sha256 "3f2bffce624326e02dae3ceb95689c55966df503e703f4c6bc5de90fbff00191"
      def install
        bin.install "eph"
      end
    end
  end

  test do
    system "#{bin}/eph", "--version"
  end
end
